application:
  title: Java Mongo
  version: 0.0.1-SNAPSHOT
  generateData: 0

environment: local

server:
  port: 8080

spring:
  application:
    name: javamongo
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/datacatalog?authSource=admin

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG