application:
  title: Java Mongo
  version: 0.0.1-SNAPSHOT

environment: local

server:
  port: 8080

spring:
  application:
    name: javamongo
  data:
    mongodb:
      host: mongo
      port: 27017
      database: datacatalog
      username: root
      password: root